language: python
python: 2.7
sudo: false
cache:
  pip: true
  directories:
  - $HOME/.pylint.d
  - eggs

global:
  - secure: "nTXMNU2aYbCtvKD74PndF8Xm2h6IvsxPjr6vj45AxjXmaB7Wf5oGi/4b6ObV\nexBtUQkFnc+M0ThGyUznOCPi3YxcbTzsyhQYhHUtmtw/6QRyYgo4E0GLDItU\n37Ff6wpxl3NMMJTvpi6SOVUvIJUl3+cs+4bkMkS48RSFGg2rGmo="  # Coveralls.io token
env:
  matrix:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
matrix:
  fast_finish: true

before_install:
- cp plone-$PLONE_VERSION.x.cfg buildout.cfg

install:
- python bootstrap.py --setuptools-version=$(curl -s https://raw.githubusercontent.com/plone/buildout.coredev/$PLONE_VERSION/requirements.txt | grep setuptools)
- bin/buildout annotate
- bin/buildout

script:
- bin/code-analysis
- bin/test
- bin/pylint --py3k --disable=no-absolute-import src/plone/api || true

after_success:
- pip install coverage
- coverage run bin/test
- pip install coveralls
- coveralls

notifications:
  irc:
    channels:
      - "irc.freenode.org#sprint"
    template:
      - "%{repository}/#%{build_number}/%{branch} (%{author}): %{message} %{build_url}"
